language: android
jdk: oraclejdk7
sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    #- sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-google-m2repository


script: gradle assembleDebugRelease

